from typing import Protocol, Iterable
from app.identidade.persistence.pessoa_orm import PessoaORM


class PessoaRepository(Protocol):
    """Contrato que define o comportamento esperado do repositório de Pessoa."""

    async def get_by_id(self, id_pessoa: int) -> PessoaORM | None: ...
    async def get_by_email(self, email: str) -> PessoaORM | None: ...
    async def list_all(self) -> Iterable[PessoaORM]: ...
    async def add(self, pessoa: PessoaORM) -> PessoaORM: ...
    async def delete(self, id_pessoa: int) -> None: ...
