from __future__ import annotations

from typing import Protocol
from collections.abc import Iterable
from uuid import UUID

from app.identidade.persistence.pessoa_orm import PessoaORM


class PessoaRepository(Protocol):
    async def create(self, pessoa: PessoaORM) -> PessoaORM: ...
    async def list_all(self) -> Iterable[PessoaORM]: ...
    async def get_by_id(self, id_pessoa: UUID) -> PessoaORM | None: ...
    async def get_by_email(self, email: str) -> PessoaORM | None: ...
    async def update(self, pessoa: PessoaORM) -> PessoaORM: ...
    async def delete(self, id_pessoa: UUID) -> None: ...
