from __future__ import annotations

from typing import Protocol
from collections.abc import Iterable
from app.identidade.persistence.sessao_orm import SessaoORM


class SessaoRepository(Protocol):
    async def create(self, sessao: SessaoORM) -> SessaoORM: ...
    async def get_by_id(self, id_sessao: int) -> SessaoORM | None: ...
    async def get_by_token_hash(self, token_hash: str) -> SessaoORM | None: ...
    async def list_by_pessoa(self, id_pessoa: int) -> Iterable[SessaoORM]: ...
    async def delete_by_id(self, id_sessao: int) -> None: ...
    async def delete_by_token_hash(self, token_hash: str) -> None: ...
    async def delete_all_for_pessoa(self, id_pessoa: int) -> int: ...
    async def purge_expired(self) -> int: ...
