version: 2
updates:
    # Enable version updates for GitHub Actions only
    # Note: Python dependencies are managed by Poetry, not pip
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"
      open-pull-requests-limit: 5
      reviewers:
          - "brunoribeirol"
      assignees:
          - "brunoribeirol"
