from __future__ import annotations

from typing import Protocol
from collections.abc import Iterable
from datetime import datetime, timedelta
from uuid import UUID

from app.alertas.persistence.alerta_orm import AlertaORM


class AlertaRepository(Protocol):
    """Contrato que define as operações para o repositório de Alertas."""

    async def get_by_id(self, id_alerta: int) -> AlertaORM | None: ...
    async def list_by_pessoa(self, id_pessoa: UUID) -> Iterable[AlertaORM]: ...
    async def list_all(self) -> Iterable[AlertaORM]: ...
    async def add(self, alerta: AlertaORM) -> AlertaORM: ...
    async def update(self, alerta: AlertaORM) -> AlertaORM: ...
    async def delete(self, id_alerta: int) -> None: ...
    async def delete_old_alertas(self, id_pessoa: UUID, older_than: datetime) -> int: ...
