from typing import Protocol, Iterable
from app.alertas.persistence.alerta_orm import AlertaORM


class AlertaRepository(Protocol):
    """Contrato que define as operações para o repositório de Alertas."""

    async def get_by_id(self, id_alerta: int) -> AlertaORM | None: ...
    async def list_by_pessoa(self, id_pessoa: int) -> Iterable[AlertaORM]: ...
    async def list_by_meta(self, id_meta: int) -> Iterable[AlertaORM]: ...
    async def list_all(self) -> Iterable[AlertaORM]: ...
    async def add(self, alerta: AlertaORM) -> AlertaORM: ...
    async def update(self, alerta: AlertaORM) -> AlertaORM: ...
    async def delete(self, id_alerta: int) -> None: ...
