from typing import Protocol, Iterable
from app.persistence.db.comercial.assinatura_orm import AssinaturaORM


class AssinaturaRepository(Protocol):
    """Contrato para operações relacionadas às assinaturas."""

    async def get_by_id(self, id_assinatura: int) -> AssinaturaORM | None: ...
    async def list_by_pessoa(self, id_pessoa: int) -> Iterable[AssinaturaORM]: ...
    async def list_by_plano(self, id_plano: int) -> Iterable[AssinaturaORM]: ...
    async def list_all(self) -> Iterable[AssinaturaORM]: ...
    async def add(self, assinatura: AssinaturaORM) -> AssinaturaORM: ...
    async def update(self, assinatura: AssinaturaORM) -> AssinaturaORM: ...
    async def delete(self, id_assinatura: int) -> None: ...
