from __future__ import annotations

from typing import Protocol
from collections.abc import Iterable  # <- usar daqui
from app.comercial.persistence.plano_orm import PlanoORM


class PlanoRepository(Protocol):
    """Contrato que define as operações de acesso a dados de Plano."""

    async def get_by_id(self, id_plano: int) -> PlanoORM | None: ...
    async def get_by_titulo(self, titulo: str) -> PlanoORM | None: ...
    async def list_all(self) -> Iterable[PlanoORM]: ...
    async def add(self, plano: PlanoORM) -> PlanoORM: ...
    async def update(self, plano: PlanoORM) -> PlanoORM: ...
    async def delete(self, id_plano: int) -> None: ...
