from typing import Protocol, Iterable
from app.metas.persistence.meta_orm import MetaORM


class MetaRepository(Protocol):
    """Contrato que define o comportamento esperado do repositório de Meta."""

    async def get_by_id(self, id_meta: int) -> MetaORM | None: ...
    async def list_by_pessoa(self, id_pessoa: int) -> Iterable[MetaORM]: ...
    async def list_all(self) -> Iterable[MetaORM]: ...
    async def add(self, meta: MetaORM) -> MetaORM: ...
    async def update(self, meta: MetaORM) -> MetaORM: ...
    async def delete(self, id_meta: int) -> None: ...
